### ISSUE TITLE
Compiling locally fails

### ISSUE THREAD

**Issue by davdave** [NicklasVraa/LiX#12]
Hello,

I am trying unsuccessfully to compile documents using LiX latex template.
I am on linux with  pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
I use TexWorks.

Error in compilation gives this: 

> lix.sty 
> 181
> Undefined control sequence.
> l.181     \NewCommandCopy
>                          {\oldabstract}{\abstract}% 
(I don't understand the meaning)

Can you give me guidance on how to make the compilation work without using Overleaf? 
Thank you

**Comment by NicklasVraa** [comment]
Hey :)

I think you are missing some of the necessary packages, probably xparse. Take a look at the github readme install section and check if you have all the packages installed.

https://github.com/NicklasVraa/LiX?tab=readme-ov-file#3-installation-

Consider starring the repository and follow my profile, if the project is useful to you :)

**Comment by davdave** [comment]
Thank you for your response. I added xparse but unfortunately it did not solve the problem. HOW can I identify which package should be called in the preamble?
Thanks in advance

**Comment by davdave** [comment]
I solved the problem by upgrading to the latest version of LaTex. 
This discussion can be removed.
