### ISSUE TITLE
Change title background

### ISSUE THREAD

**Issue by Xergon-sci** [NicklasVraa/LiX#14]
The novel and textbook both add titles on the conver pages. Depending on the cover used, the title is not always readable. Is there an option to draw a plain colored rectangle behind the title, author and date? I tried with different packages, but each gave its own errors.

**Comment by NicklasVraa** [comment]
\cover{path/to/front.pdf}{path/to/back.pdf} 
The images have to be pdf-files. The starred version will not print the title, author, etc. on top of the cover. This is useful, if the cover already includes these. Should be called before \begin{document}.

So if you write \cover*{... then the titles will not be printed. I usually design the titles separately within the pdf that make up front cover.

Hope this helps :)
