### ISSUE TITLE
\L variables clash with polish alphabet letter Ł

### ISSUE THREAD

**Issue by Megaemce** [NicklasVraa/LiX#4]
Hi Nicklas, thank you for creating this project.
I am actively using it right now but I just noticed one small issues when writing in polish.
You have created new variable \L however it's worth understanding that \L it's also asigned to a polish letter Ł which makes your template almost useless for writing in polish. I can simply rename the variable but instead I decided to write you this issue - simply so you know! 

There might be also another clashes with \H variable with different special characters. Maybe it's worth to rename the short variables to something less prone to clashes? 

See: 
https://en.wikibooks.org/wiki/LaTeX/Special_Characters
https://tex.stackexchange.com/a/8859

**Comment by NicklasVraa** [comment]
You are more than welcome to change the names of any commands you wish. Make the class your own :)

That said, I will definitely consider if longer command names are worth the higher compatibility with languages other than English. Thanks for the feedback.
