### ISSUE TITLE
Custom paper size not working

### ISSUE THREAD

**Issue by bfelbo** [NicklasVraa/LiX#5]
Hej Nicklas, seems like an cool project!

I'm trying to use your [Overleaf novella template](https://www.overleaf.com/latex/templates/lix-novella-class/twgsfpmcqhsv) with a custom size. However, I get the following errors when I use `\size{custom}{6in}{9in}` described in the README:

```
Package xkeyval Error: `custompaper' undefined in families `Gm'.
Package xkeyval Error: `6in' undefined in families `Gm'.
LaTeX Error: Missing \begin{document}.
```

**Comment by NicklasVraa** [comment]
I'll check it out tomorrow. Thanks for reporting it:)

**Comment by NicklasVraa** [comment]
Actually, this feature was implemented after I uploaded templates to overleaf (a couple of months ago). Try to replace lix.sty in overleaf with the latest one from this repository. I'll add a disclaimer to the readme. Please report back if this helped:)

**Comment by bfelbo** [comment]
Yep, that worked. Thanks!
