### ISSUE TITLE
\fig command undefined

### ISSUE THREAD

**Issue by lucalevi** [NicklasVraa/LiX#6]
I am using the class novella to write a book, and this is the beginning of my main.tex file:

`\documentclass{novella}
\usepackage{quoting}`

In a chapter, I want to insert a figure, and I am doing it in this way:
`\fig{fig:myfigurer}{0.5}{myfigure.jpeg}
`

I get an error when compiling: undefined control sequence, referencing the command \fig above. 
How to properly insert an image using the class novella? Thanks!

Note: I am compiling offline using TeXshop. Other command like those to modify the style (bold, italics...) of the text work

**Comment by NicklasVraa** [comment]
If I remember correctly, the novella class does not import the figure part of LiX. This was a design decision, as novellas tend not to have figures.

You can easily modify the novella class to also import that part by adding `figures` to `\RequirePackage[basics, ...]{lix}`

**Comment by lucalevi** [comment]
It worked indeed! Just added 
`\RequirePackage[..., figures]{lix}` to the class novella.cls and here I am, with a nice figure at the top of my chapter!
Thanks Nicklas! ;)
