### ISSUE TITLE
Page X of ?? on local instance

### ISSUE THREAD

**Issue by psweet** [NicklasVraa/LiX#8]
Hello! I've followed your installation instructions and am able to compile everything perfectly except for the top right header on the contract template. This is what I see:
![image](https://github.com/NicklasVraa/LiX/assets/49662397/1ddb2816-5451-429f-a613-ffa9bdffd870)
Any idea what might be causing this?

**Comment by NicklasVraa** [comment]
Do you have [lastpage](https://ctan.org/pkg/lastpage?lang=en) installed?

**Comment by psweet** [comment]
I just checked and lastpage is installed, and that import line is also present on `lix.sty`. I'll continue to do some testing and see if I can figure it out

**Comment by psweet** [comment]
It appears it was a problem with `\&` in the document. I am unsure what they were doing, but removing them fixed the problem.
