### ISSUE TITLE
Problem using different language

### ISSUE THREAD

**Issue by kartr439** [NicklasVraa/LiX#9]
Hi! I was trying out this package in Swedish and all special characters (å, ä, ö) is replaced by **??** in the PDF even though i used \lang {swedish}. Is there any way to solve this?

**Comment by NicklasVraa** [comment]
Are you using the template on Overleaf? I had the same issue with Danish, so I fixed it and updated the package here :)

**Comment by kartr439** [comment]
Ah yes I was! Replacing them fixed it directly, thank you so much! :)
